version: '3'
#
# NB, no specific volumes set, data storage will default to /var/lib/docker/volumes on ubuntu
# clean up with docker volume prune
#
services:

  sbrrr2-influxdb:
    build:
      context: .
      dockerfile: test-container-config/influxdb/Dockerfile
    ports:
      - "127.0.0.1:8186:8086"
    env_file:
      - 'test-container-config/influxdb/influxdb.env'
    network_mode: "host"
  sbrrr2-grafana:
    build:
      context: .
      dockerfile: test-container-config/grafana/Dockerfile
    ports:
      - "127.0.0.1:4000:3000"
    env_file:
      - 'test-container-config/grafana/grafana.env'
    depends_on:
      - sbrrr2-influxdb
    network_mode: "host"
  sbrrr2-demo:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - sbrrr2-influxdb
    network_mode: "host"